# Generated by Django 3.2.12 on 2022-03-10 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('length', models.FloatField(verbose_name='Расстояние')),
            ],
        ),
    ]
