# Generated by Django 3.2.12 on 2022-03-10 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='ObjectName',
        ),
    ]
